spec:
  template:
    spec:
      # Declare a volume mounting the config map
      volumes:
        - name: config
          configMap:
            name: app-config
      containers:
        - name: vertx
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_OPTIONS
              value: '-Dvertx.cacheDirBase=/tmp -Dvertx.jgroups.config=default-configs/default-jgroups-kubernetes.xml -Djava.net.preferIPv4Stack=true'
            - name: JAVA_ARGS
              value: '-cluster'
          # Mount the volume define above in /deployments/config
          volumeMounts:
            - name: config
              mountPath: /deployments/src/kubernetes
